# Generated by Django 5.1.4 on 2025-01-09 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0009_userprofile_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
