# Generated by Django 5.1.4 on 2025-01-09 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0010_remove_userprofile_email_remove_userprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='repeated_password',
        ),
    ]
