# Generated by Django 5.1.4 on 2025-01-09 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0016_alter_userprofile_description_alter_userprofile_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone',
            new_name='tel',
        ),
    ]
