# Generated by Django 5.1.4 on 2025-01-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0018_userprofile_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to='profile_pictures/'),
        ),
    ]
