# Generated by Django 5.1.4 on 2025-01-23 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0001_initial'),
        ('user_auth_app', '0019_alter_fileupload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='delivery_time_in_days',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='features',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='offer_type',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='revisions',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='title',
        ),
        migrations.AddField(
            model_name='orders',
            name='offer_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='business_user',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='customer_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth_app.userprofile'),
        ),
    ]
