# Generated by Django 5.1.4 on 2025-01-23 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders_app', '0002_remove_orders_delivery_time_in_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='offer_id',
            new_name='offer_detail_id',
        ),
    ]
