# Generated by Django 5.1.4 on 2025-01-24 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0014_remove_offerdetail_features_offerdetail_features'),
        ('orders_app', '0003_rename_offer_id_orders_offer_detail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='offer_detail_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers_app.offerdetail'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('in_progress', 'in_progress'), ('completed', 'completed')], default='in_progress', max_length=255),
        ),
    ]
