# Generated by Django 5.1.4 on 2025-01-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additionalfunctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercount',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
    ]
