# Generated by Django 5.1.4 on 2025-01-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additionalfunctions', '0003_ratingandreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingandreview',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='ratingandreview',
            name='review_count',
        ),
        migrations.AddField(
            model_name='ratingandreview',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='ratingandreview',
            name='review',
            field=models.CharField(default='', max_length=500),
        ),
    ]
