# Generated by Django 5.1.4 on 2025-01-31 13:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additionalfunctions', '0005_rename_user_ratingandreview_business_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingandreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratingandreview',
            name='reviewer',
            field=models.IntegerField(default=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratingandreview',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
