# Generated by Django 5.1.4 on 2025-01-15 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0001_initial'),
        ('user_auth_app', '0019_alter_fileupload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='offerdetail',
            name='url',
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='delivery_time_in_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='offer_type',
            field=models.CharField(choices=[('Basic Design', 'Basic Design'), ('Standard Design', 'Standard Design'), ('Premium Design', 'Premium Design')], default='Basic Design', max_length=255),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='revisions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='title',
            field=models.CharField(default='title', max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='user_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_offers', to='user_auth_app.userprofile'),
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='features',
            field=models.ManyToManyField(related_name='offers', to='offers_app.feature'),
        ),
    ]
