# Generated by Django 5.1.4 on 2025-01-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0003_alter_offerdetail_offer_type_alter_offerdetail_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='offer_type',
            field=models.CharField(choices=[('Basic', 'basic'), ('Standard', 'standard'), ('Premium', 'premium')], default='Basic Design', max_length=255),
        ),
    ]
