# Generated by Django 5.1.4 on 2025-01-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0005_alter_offerdetail_offer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerdetail',
            name='offer_type',
            field=models.CharField(choices=[('basic', 'basic'), ('standard', 'standard'), ('premium', 'premium')], default='basic', max_length=255),
        ),
        migrations.AlterField(
            model_name='offerdetail',
            name='title',
            field=models.CharField(choices=[('Basic Design', 'Basic Design'), ('Standard Design', 'Standard Design'), ('Premium Design', 'Premium Design')], default='Basic Design', max_length=255),
        ),
    ]
