# Generated by Django 5.1.4 on 2025-01-18 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0006_alter_offerdetail_offer_type_alter_offerdetail_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='min_delivery_time',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='min_price',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='user_details',
        ),
    ]
