# Generated by Django 5.1.4 on 2025-01-19 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0008_singleoffer'),
        ('user_auth_app', '0019_alter_fileupload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleoffer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth_app.userprofile'),
        ),
    ]
