# Generated by Django 5.1.4 on 2025-01-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0009_alter_singleoffer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SingleOffer',
        ),
    ]
