# Generated by Django 5.1.4 on 2025-01-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers_app', '0012_alter_offer_updated_at_remove_offerdetail_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerdetail',
            name='features',
        ),
        migrations.AddField(
            model_name='offerdetail',
            name='features',
            field=models.ManyToManyField(related_name='offers', to='offers_app.feature'),
        ),
    ]
